# Generated by Django 4.1.4 on 2023-02-11 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, unique=True)),
                ("posterImage", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, unique=True)),
                ("teamName", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=10)),
                ("location", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("description", models.CharField(max_length=10000)),
                ("tagline", models.CharField(max_length=2000)),
                ("posterImage", models.CharField(max_length=1000)),
                ("organisers", models.JSONField()),
                ("volunteer", models.JSONField()),
                ("isTeamEvent", models.BooleanField()),
                ("teamParticapantCount", models.PositiveIntegerField()),
                ("isClosed", models.BooleanField()),
                ("status", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profilePic", models.CharField(max_length=100)),
                ("bio", models.CharField(blank=True, max_length=500)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=10)),
                ("otp", models.CharField(blank=True, max_length=6)),
                ("events", models.JSONField()),
                ("isVolunteer", models.BooleanField()),
                ("isOrganiser", models.BooleanField()),
                ("notification", models.JSONField()),
                ("isAccountSetup", models.BooleanField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="User",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comments", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("qrCodeData", models.CharField(max_length=64)),
                ("userCount", models.PositiveIntegerField()),
                ("paymentMethod", models.CharField(max_length=100)),
                ("isScanned", models.BooleanField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.event"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.profile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateTime", models.DateTimeField()),
                ("isRead", models.BooleanField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.event"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_user",
                        to="api.profile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="coordinator1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coordinator1_event",
                to="api.profile",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="coordinator2",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coordinator2_event",
                to="api.profile",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.department"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="teamLeader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_teamLeader",
                to="api.profile",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="winner1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_winner1",
                to="api.profile",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="winner2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_winner2",
                to="api.profile",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="winner3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_winner3",
                to="api.profile",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="coordinator1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="department_coordinator1",
                to="api.profile",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="coordinator2",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="department_coordinator2",
                to="api.profile",
            ),
        ),
    ]
