# Generated by Django 4.1.4 on 2023-02-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_profile_events_alter_profile_isaccountsetup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="round1",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="round2",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="round3",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="round4",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="round5",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="rules",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
