# Generated by Django 4.1.4 on 2023-02-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_event_round1_event_round2_event_round3_event_round4_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="winnerPrice1",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="winnerPrice2",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
