# Generated by Django 4.1.4 on 2023-02-17 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_event_teamprice"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="events",),
        migrations.RemoveField(model_name="profile", name="notification",),
    ]
