# Generated by Django 4.1.4 on 2023-02-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_gallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="abbriviation",
            field=models.CharField(default="", max_length=10),
        ),
    ]
