# Generated by Django 4.1.4 on 2023-02-21 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_remove_event_coordinator1_remove_event_coordinator2_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="bio",),
        migrations.RemoveField(model_name="profile", name="birth_date",),
    ]
