# Generated by Django 4.1.4 on 2023-02-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_ticket_ispaid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket", name="date", field=models.DateField(auto_now_add=True),
        ),
    ]
