# Generated by Django 4.1.4 on 2023-02-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_ticket_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="comments",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="isScanned",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="userCount",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
