# Generated by Django 4.1.4 on 2023-02-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_ticket_comments_alter_ticket_isscanned_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="paymentMethod",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
