# Generated by Django 4.1.4 on 2023-02-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_ticket_owner1_ticket_owner2_ticket_owner3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="isCampainVolunteer",
            field=models.BooleanField(default=False),
        ),
    ]
