# Generated by Django 4.1.4 on 2023-02-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_profile_iscampainvolunteer"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="isTeamPriceFull",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="teamParticapantCountMin",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="event",
            name="price",
            field=models.CharField(default="-", max_length=10),
        ),
        migrations.AlterField(
            model_name="event",
            name="teamParticapantCount",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="event",
            name="teamPrice",
            field=models.CharField(default="-", max_length=10),
        ),
    ]
