# Generated by Django 4.1.3 on 2023-03-01 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_event_isteampricefull_event_teamparticapantcountmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='acceptedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptedBy', to='api.profile'),
        ),
    ]
