# Generated by Django 4.1.4 on 2023-03-03 07:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alter_ticket_acceptedby"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="images",
            field=models.JSONField(default=api.models.Event.default_images),
        ),
    ]
