# Generated by Django 4.1.4 on 2024-02-01 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_event_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="organiser6",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organiser6_event",
                to="api.profile",
            ),
        ),
    ]
