# Generated by Django 4.1.4 on 2024-02-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0028_event_winnerprice3"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="organisers",
        ),
        migrations.RemoveField(
            model_name="event",
            name="volunteer",
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.CharField(max_length=100),
        ),
    ]
