# Generated by Django 4.1.4 on 2024-02-01 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_remove_event_winner1_remove_event_winner2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="organiser6",
        ),
    ]
