# Generated by Django 4.1.4 on 2024-02-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0031_remove_event_organiser6"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
