# Generated by Django 4.1.4 on 2024-02-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0032_event_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="link",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
