# Generated by Django 4.1.4 on 2024-02-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0033_alter_event_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="foodCoupon",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="profile",
            name="isScannedCoupon",
            field=models.BooleanField(default=False),
        ),
    ]
