# Generated by Django 4.1.4 on 2024-02-04 03:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0034_profile_foodcoupon_profile_isscannedcoupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.JSONField(default=api.models.Profile.location_data),
        ),
    ]
