# Generated by Django 4.1.4 on 2024-02-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0035_profile_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="maxTicket",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
