# Generated by Django 4.1.4 on 2024-02-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0037_profile_foodcoupon2_profile_isscannedcoupon2"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="isAllumni",
            field=models.BooleanField(default=False),
        ),
    ]
